ecs_cluster_name = "lfchin-ecs-cluster-dev"
ecs_service_name = "lfchin-ecs-service-dev"
ecs_task_defn_family = "lfchin-ecs-task-def-dev"
ecs_container_name = "lfchin-container-dev"
ecs_port_name = "lfchin-3000-tcp-dev"
