ecs_cluster_name = "lfchin-ecs-cluster-prod"
ecs_service_name = "lfchin-ecs-service-prod"
ecs_task_defn_family = "lfchin-ecs-task-def-prod"
ecs_container_name = "lfchin-container-prod"
ecs_port_name = "lfchin-3000-tcp-prod"
