ecs_cluster_name = "lfchin-ecs-cluster-uat"
ecs_service_name = "lfchin-ecs-service-uat"
ecs_task_defn_family = "lfchin-ecs-task-def-uat"
ecs_container_name = "lfchin-container-uat"
ecs_port_name = "lfchin-3000-tcp-uat"
